name: Test PR
on:
  pull_request:
    types: [opened, synchronize]
concurrency: ci-${{ github.event.pull_request.head.ref}}
jobs:
  build-and-test:
    uses: ./.github/workflows/test-common.yml
    with:
      ref: ${{ github.event.pull_request.head.ref }}
